### ISSUE TITLE
no module named cryptoalgotrading

### ISSUE THREAD

**Issue by Chau1985** [ivopetiz/algotrading#10]
When running cryptoalgotrading.py file I get the following error:
    import cryptoalgotrading.var as var
ImportError: No module named var

And other files says there is no module named cryptoalgotrading.

**Comment by ivopetiz** [comment]
Are you trying to run cryptoalgotrading.py or you got this error importing it?
Have you tried the 'How to start' section in README.md?

**Comment by Chau1985** [comment]
I have tried two things:
1. I tried to run test.py file, where I got the message that there is 'no module named cryptoalgotrading'
2. I also tried running the cryptoalgotrading.py and I got the 'import cryptoalgotrading.var as var
ImportError: No module named var' message. 

I have followed the README.md till the script section. Actually after that I don't really understand how to activate the program. I am just trying to figure it out with the knowledge I have on Python

**Comment by ivopetiz** [comment]
You shouldn't run cryptoalgotrading as a program. Instead, you need to import cryptoalgotrading to be able to use it in your programs. Cryptoalgotrading alone will not do anything, it is a lib. You can follow the examples in [here](https://github.com/ivopetiz/algotrading#examples).
You can run it using Python3, in Ipython or Jupyter notebook for example.
