### ISSUE TITLE
Error in Readme - could cause confusion to users

### ISSUE THREAD

**Issue by smfxfc** [ivopetiz/algotrading#11]
https://github.com/ivopetiz/algotrading#entry-functions

Entry functions aggregate all strategies to enter in a specific market. Once data fill all the requisites to enter a specific market, an action is taken. Users can use one or several functions in the same call, to fill the requisites and enter market/markets. Functions should return True, if the available data represent an **exit point** for the user. If not, the return needs to be False. <entry.py> should aggregate all users entry functions.

"Exit point" should be "entry point" here. Feel free to make the quick fix yourself, or assign my way.

**Comment by ivopetiz** [comment]
Thanks for the correction.
