### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by HAGAI123** [ivopetiz/algotrading#15]
**### hello i have couple problem , 
this is the first** 

, 
line 17, in <module>
    import cryptoalgotrading.var as var
ModuleNotFoundError: No module named 'cryptoalgotrading.var'; 'cryptoalgotrading' is not a package

and the other one is , 
is when i run  pip install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement matplotlib==2.2.2
ERROR: No matching distribution found for matplotlib==2.2.2
 

**### if i change in the requirements the matplotlib from 2.2.2 to 3.4.1 so is make me now** 

ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zth40e8e/tables_2311501a8cfc4ba59fb36049f3ffb3bd/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zth40e8e/tables_2311501a8cfc4ba59fb36049f3ffb3bd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-xho4ah8s
         cwd: /tmp/pip-install-zth40e8e/tables_2311501a8cfc4ba59fb36049f3ffb3bd/
    Complete output (13 lines):
    /tmp/H5closezd786i5e.c: In function ‘main’:
    /tmp/H5closezd786i5e.c:2:5: warning: implicit declaration of function ‘H5close’ [-Wimplicit-function-declaration]
        2 |     H5close();
          |     ^~~~~~~
    /usr/bin/ld: cannot find -lhdf5
    collect2: error: ld returned 1 exit status
    * Using Python 3.8.5 (default, Jan 27 2021, 15:41:15)
    * USE_PKGCONFIG: True
    * Found conda env: ``/home/hagai123/miniconda3``
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/73/51/6dabb2b94826e5db3aa2542b80f1382780b96a0cd13e0cfb637b36ede5c5/tables-3.5.2.tar.gz#sha256=b220e32262bab320aa41d33125a7851ff898be97c0de30b456247508e2cc33c2 (from https://pypi.org/simple/tables/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement tables==3.5.2
ERROR: No matching distribution found for tables==3.5.2

**and then if i change the tables from 3.5.2 to 3.6.1
so is make me this** 

ERROR: Cannot install matplotlib==3.4.1 and pyparsing==2.2.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pyparsing==2.2.0
    matplotlib 3.4.1 depends on pyparsing>=2.2.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Comment by ivopetiz** [comment]
Hi @HAGAI123, thanks for opening this issue. Tables and Matplotlib were updated on requirements.txt, so I hope you can install all the dependencies now.
