### ISSUE TITLE
 ERROR: Could not find a version that satisfies the requirement pandas==1.2.0 

### ISSUE THREAD

**Issue by bruciebruce** [ivopetiz/algotrading#23]
Hello,

I tried running

pip install -r requirements.txt 

with a python virtual env for python 3.6 and 3 and am running into this issue.
What version of python should I be using?

Thank you very much!

**Comment by ivopetiz** [comment]
Hi there, 
Pandas dropped support for Python 3.6, in versions >=1.2.
I suggest you use version 3.8.5.

Thanks.

**Comment by bruciebruce** [comment]
Hello,

You were right, 3.8.7 did the trick.

Next question if I may, Chronograf is now longer free or available as you have it in your install script.

What replacement would you recommend for Chronograf?  Would Grafana work?

Thanks again.

**Comment by ivopetiz** [comment]
Hi,

Didn't know that. I'm using an old version and didn't update it. 

Grifana works well and maybe looks better than Chronograf. I just use Chronograf because it was easier to configure at the time and for the simple things I do, it works fine.

**Comment by bruciebruce** [comment]
I tried installing fluxdb as a native linux service and Chronograf as a docker containter, but could not get Chronograf to connect to fluxdb.

I disabled the fluxdb service and installed a docker container for fluxdb.

It appears that using fluxdb and Chronograf both as containers should work.

I followed the steps found here: https://hub.docker.com/_/chronograf
