### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by vahidalvandi** [ivopetiz/algotrading#30]
Hello, thank you for publishing this project
I have been researching digital currency exchange for some time and I really do not know where to start. I am more interested in working with Python and need guidance on what the database structure and data type should look like. Thanks for taking the time to guide me.

**Comment by ivopetiz** [comment]
Hi @vahidalvandi,

I separate this project into 2 repositories. The database part is in [here](https://github.com/ivopetiz/crypto-database)

**Comment by vahidalvandi** [comment]
hi @ivopetiz  
i found another poroject https://github.com/fluidex/dingir-exchange
What do you think about it?

**Comment by ivopetiz** [comment]
I don't know the project

**Comment by vahidalvandi** [comment]
What exchanges is your project currently using?
I am a Laravel programmer, I decide to proceed with some parts, such as authentication or deposit and withdrawal or placing an order through Laravel and eventually execute transactions with your project .

This is possible??

**Comment by ivopetiz** [comment]
no. it's easier to use the official API to execute transactions than adapt this project just for that.

**Comment by vahidalvandi** [comment]
I want to create a membership + deposit and withdrawal system with Laravel and then enter sales orders into this engine that you wrote.
In fact, you made this project for this purpose, right?

**Comment by ivopetiz** [comment]
not exactly. the idea is to automate your trading strategies through algorithms that you write and run backtests to test your algorithms.
